"""The SecretStore repository contract — the domain's port to a secret backend.

Everything above the infrastructure layer depends on this Protocol, never on the
Databricks SDK. Tests and the real adapter both satisfy it structurally.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from .models import Acl, Identity, Scope, Secret


@runtime_checkable
class SecretStore(Protocol):
    """Port: everything the app needs from a workspace's secret backend."""

    profile: str | None

    def whoami(self) -> Identity: ...
    def list_scopes(self) -> list[Scope]: ...
    def create_scope(self, name: str) -> None: ...
    def delete_scope(self, name: str) -> None: ...
    def list_secrets(self, scope: str) -> list[Secret]: ...
    def get_secret_value(self, scope: str, key: str) -> str: ...
    def put_secret(self, scope: str, key: str, value: str) -> None: ...
    def delete_secret(self, scope: str, key: str) -> None: ...
    def list_acls(self, scope: str) -> list[Acl]: ...
    def put_acl(self, scope: str, principal: str, permission: str) -> None: ...
    def delete_acl(self, scope: str, principal: str) -> None: ...
